### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by GiancarloMassoni** [GiancarloMassoni/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [ ] Add classes to css for each rotation
- [ ] Add DOM for the car
- [ ] On each arrow press change the class for the car
