### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by GiancarloMassoni** [GiancarloMassoni/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [ ] Add a data model that includes the location of the car
- [ ] Add absolute positioning
- [ ] On spacebar pressed change the style of top and left of the car
- [ ] Add a interval that does it in 16 milliseconds
